apiVersion: constraints.gatekeeper.sh/v1beta1
kind: gkeBlockExternalLb
metadata:
  name: block-external-lb
spec:
  # enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    namespaces:
      - "staging"
