apiVersion: v1
kind: Service
metadata:
  name: block-external-lb
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
