apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gkeblockexternallb
  annotations:
    description: "Only internal gke loadbalancer is allowed"
spec:
  crd:
    spec:
      names:
        kind: gkeBlockExternalLb
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package gkeblockexternallb

        violation[{"msg": msg}] {
          input.review.object.kind == "Service"
          service := input.review.object
          service.spec.type == "LoadBalancer"
          not service.metadata.annotations["cloud.google.com/load-balancer-type"] == "Internal"
          msg := sprintf("Only internal loadbalancer is allowed:  %v", [service.metadata.name])
        }
