apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gkeblockexternallb
  annotations:
    description: "Restricting loadbalancer must have internal annotations."
spec:
  crd:
    spec:
      names:
        kind: gkeBlockExternalLb
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package gkeblockexternallb

        violation[{"msg": msg}] {
            input.request.kind.kind == "Service"
            input.request.object.spec.type == "LoadBalancer"
            not input.request.object.metadata.annotations["cloud.google.com/load-balancer-type"] == "Internal"

            msg := "err, gke LoadBalancer must have Internal annotation."
        }
