apiVersion: constraints.gatekeeper.sh/v1beta1
kind: gkeBlockExternalLb
metadata:
  name: block-external-lb
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    excludedNamespaces:
      - "kube-system"
