apiVersion: v1
kind: Service
metadata:
  name: allowed-internal-lb
  annotations:
    "cloud.google.com/load-balancer-type": "Internal"
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
